from flask import Flask, render_template, request, redirect, url_for, jsonify, send_file
import os
from data_handler import DataHandler
from pdf_template import PDFGenerator
from chart_generator import ChartGenerator
from datetime import datetime

app = Flask(__name__)
app.config['SECRET_KEY'] = 'your-secret-key-here'

# ตั้งค่าโฟลเดอร์เก็บไฟล์
UPLOAD_FOLDER = 'static/uploads'
CHART_FOLDER = 'static/charts'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(CHART_FOLDER, exist_ok=True)

# สร้างตัวจัดการข้อมูล
data_handler = DataHandler()
chart_gen = ChartGenerator()

@app.route('/')
def index():
    return redirect(url_for('dashboard'))

    @app.route('/dashboard')
    def dashboard():
        """หน้าแดชบอร์ดหลัก"""
            transactions = data_handler.load_data_from_db()
                summary = data_handler.get_summary()
                    
                        # สร้างกราฟ
                            chart_path = os.path.join(CHART_FOLDER, 'summary_chart.png')
                                if summary['by_category']:
                                        chart_gen.create_category_chart(summary['by_category'], chart_path)
                                            
                                                return render_template('dashboard.html', 
                                                                         transactions=transactions[:5],  # แสดง 5 รายการล่าสุด
                                                                                                  summary=summary,
                                                                                                                           chart_path=chart_path if os.path.exists(chart_path) else None)

                                                                                                                           @app.route('/reports')
                                                                                                                           def reports():
                                                                                                                               """หน้ารายงาน"""
                                                                                                                                   transactions = data_handler.load_data_from_db()
                                                                                                                                       summary = data_handler.get_summary()
                                                                                                                                           
                                                                                                                                               return render_template('reports.html', 
                                                                                                                                                                        transactions=transactions,
                                                                                                                                                                                                 summary=summary)

                                                                                                                                                                                                 @app.route('/data-entry')
                                                                                                                                                                                                 def data_entry():
                                                                                                                                                                                                     """หน้าเพิ่มข้อมูล"""
                                                                                                                                                                                                         categories = data_handler.get_categories()
                                                                                                                                                                                                             return render_template('data_entry.html', categories=categories)

                                                                                                                                                                                                             @app.route('/chart-view')
                                                                                                                                                                                                             def chart_view():
                                                                                                                                                                                                                 """หน้าดูกราฟ"""
                                                                                                                                                                                                                     summary = data_handler.get_summary()
                                                                                                                                                                                                                         
                                                                                                                                                                                                                             # สร้างกราฟต่างๆ
                                                                                                                                                                                                                                 charts = {}
                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                         # กราฟประเภทรายการ
                                                                                                                                                                                                                                             if summary['by_category']:
                                                                                                                                                                                                                                                     chart_path = os.path.join(CHART_FOLDER, 'category_chart.png')
                                                                                                                                                                                                                                                             chart_gen.create_category_chart(summary['by_category'], chart_path)
                                                                                                                                                                                                                                                                     charts['category'] = chart_path
                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             # กราฟรายเดือน
                                                                                                                                                                                                                                                                                 if summary['monthly']:
                                                                                                                                                                                                                                                                                         chart_path = os.path.join(CHART_FOLDER, 'monthly_chart.png')
                                                                                                                                                                                                                                                                                                 chart_gen.create_monthly_chart(summary['monthly'], chart_path)
                                                                                                                                                                                                                                                                                                         charts['monthly'] = chart_path
                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                 return render_template('chart_view.html', charts=charts)

                                                                                                                                                                                                                                                                                                                 @app.route('/add-transaction', methods=['POST'])
                                                                                                                                                                                                                                                                                                                 def add_transaction():
                                                                                                                                                                                                                                                                                                                     """เพิ่มรายการใหม่"""
                                                                                                                                                                                                                                                                                                                         name = request.form.get('name')
                                                                                                                                                                                                                                                                                                                             category = request.form.get('category')
                                                                                                                                                                                                                                                                                                                                 amount = float(request.form.get('amount'))
                                                                                                                                                                                                                                                                                                                                     date = request.form.get('date')
                                                                                                                                                                                                                                                                                                                                         description = request.form.get('description', '')
                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                 data_handler.add_record(name, category, amount, date, description)
                                                                                                                                                                                                                                                                                                                                                     return redirect(url_for('data_entry'))

                                                                                                                                                                                                                                                                                                                                                     @app.route('/generate-pdf')
                                                                                                                                                                                                                                                                                                                                                     def generate_pdf():
                                                                                                                                                                                                                                                                                                                                                         """สร้าง PDF รายงาน"""
                                                                                                                                                                                                                                                                                                                                                             transactions = data_handler.load_data_from_db()
                                                                                                                                                                                                                                                                                                                                                                 summary = data_handler.get_summary()
                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                         # สร้างกราฟสำหรับ PDF
                                                                                                                                                                                                                                                                                                                                                                             chart_path = os.path.join(CHART_FOLDER, 'pdf_chart.png')
                                                                                                                                                                                                                                                                                                                                                                                 if summary['by_category']:
                                                                                                                                                                                                                                                                                                                                                                                         chart_gen.create_bar_chart(summary['by_category'], chart_path)
                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                 # สร้าง PDF
                                                                                                                                                                                                                                                                                                                                                                                                     pdf_gen = PDFGenerator("รายงาน_บัทึกลงไดฟ์.pdf")
                                                                                                                                                                                                                                                                                                                                                                                                         pdf_gen.generate_report("รายงานบัทึกลงไดฟ์", summary, transactions, chart_path)
                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                 return send_file("รายงาน_บัทึกลงไดฟ์.pdf", as_attachment=True)

                                                                                                                                                                                                                                                                                                                                                                                                                 @app.route('/delete/<int:transaction_id>')
                                                                                                                                                                                                                                                                                                                                                                                                                 def delete_transaction(transaction_id):
                                                                                                                                                                                                                                                                                                                                                                                                                     """ลบรายการ"""
                                                                                                                                                                                                                                                                                                                                                                                                                         data_handler.db.delete_transaction(transaction_id)
                                                                                                                                                                                                                                                                                                                                                                                                                             return redirect(url_for('reports'))

                                                                                                                                                                                                                                                                                                                                                                                                                             if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                 app.run(debug=True, host='0.0.0.0', port=5000)

                                                                                                                                                                                                                                                                                                                                                                                                                                 