import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import os

class ChartGenerator:
    def __init__(self):
            # ตั้งค่าฟอนต์ภาษาไทย
                    plt.rcParams['font.sans-serif'] = ['Tahoma', 'Arial Unicode MS', 'DejaVu Sans']
                            plt.rcParams['axes.unicode_minus'] = False
                                
                                    def create_category_chart(self, data, output_file="category_chart.png"):
                                            """สร้างกราฟประเภทรายการ"""
                                                    categories = [item[0] for item in data]
                                                            amounts = [item[1] for item in data]
                                                                    
                                                                            # สร้างกราฟวงกลม
                                                                                    plt.figure(figsize=(10, 8))
                                                                                            plt.pie(amounts, labels=categories, autopct='%1.1f%%', startangle=90)
                                                                                                    plt.title('สรุปตามประเภทรายการ')
                                                                                                            plt.axis('equal')
                                                                                                                    plt.savefig(output_file, dpi=300, bbox_inches='tight')
                                                                                                                            plt.close()
                                                                                                                                    return output_file
                                                                                                                                        
                                                                                                                                            def create_monthly_chart(self, data, output_file="monthly_chart.png"):
                                                                                                                                                    """สร้างกราฟรายเดือน"""
                                                                                                                                                            months = [item[0] for item in data]
                                                                                                                                                                    amounts = [item[1] for item in data]
                                                                                                                                                                            
                                                                                                                                                                                    # สร้างกราฟเส้น
                                                                                                                                                                                            plt.figure(figsize=(12, 6))
                                                                                                                                                                                                    plt.plot(months, amounts, marker='o', linewidth=2, markersize=8)
                                                                                                                                                                                                            plt.title('สรุปรายเดือน')
                                                                                                                                                                                                                    plt.xlabel('เดือน')
                                                                                                                                                                                                                            plt.ylabel('ยอดเงิน (บาท)')
                                                                                                                                                                                                                                    plt.xticks(rotation=45)
                                                                                                                                                                                                                                            plt.grid(True, alpha=0.3)
                                                                                                                                                                                                                                                    plt.tight_layout()
                                                                                                                                                                                                                                                            plt.savefig(output_file, dpi=300, bbox_inches='tight')
                                                                                                                                                                                                                                                                    plt.close()
                                                                                                                                                                                                                                                                            return output_file
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                    def create_bar_chart(self, data, output_file="bar_chart.png"):
                                                                                                                                                                                                                                                                                            """สร้างกราฟแท่ง"""
                                                                                                                                                                                                                                                                                                    categories = [item[0] for item in data]
                                                                                                                                                                                                                                                                                                            amounts = [item[1] for item in data]
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            # สร้างกราฟแท่ง
                                                                                                                                                                                                                                                                                                                                    plt.figure(figsize=(10, 6))
                                                                                                                                                                                                                                                                                                                                            bars = plt.bar(range(len(categories)), amounts, color='skyblue')
                                                                                                                                                                                                                                                                                                                                                    plt.title('สรุปตามประเภทรายการ')
                                                                                                                                                                                                                                                                                                                                                            plt.xlabel('ประเภทรายการ')
                                                                                                                                                                                                                                                                                                                                                                    plt.ylabel('ยอดเงิน (บาท)')
                                                                                                                                                                                                                                                                                                                                                                            plt.xticks(range(len(categories)), categories, rotation=45, ha='right')
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                            # เพิ่มค่าบนแท่ง
                                                                                                                                                                                                                                                                                                                                                                                                    for i, (bar, amount) in enumerate(zip(bars, amounts)):
                                                                                                                                                                                                                                                                                                                                                                                                                plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                     f'{amount:.0f}', ha='center', va='bottom')
                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                     plt.tight_layout()
                                                                                                                                                                                                                                                                                                                                                                                                                                                             plt.savefig(output_file, dpi=300, bbox_inches='tight')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     plt.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return output_file