import pandas as pd
from datetime import datetime
import json
from database import DatabaseManager

class DataHandler:
    def __init__(self):
            self.db = DatabaseManager()
                    self.data = []
                        
                            def load_data_from_db(self):
                                    """โหลดข้อมูลจากฐานข้อมูล"""
                                            self.data = self.db.get_transactions()
                                                    return self.data
                                                        
                                                            def add_record(self, name, category, amount, date, description=""):
                                                                    """เพิ่มรายการใหม่ลงในฐานข้อมูล"""
                                                                            self.db.add_transaction(name, category, amount, date, description)
                                                                                    return True
                                                                                        
                                                                                            def get_summary(self):
                                                                                                    """ดึงสรุปข้อมูล"""
                                                                                                            summary = {}
                                                                                                                    
                                                                                                                            # สรุปตามประเภท
                                                                                                                                    category_summary = self.db.get_summary_by_category()
                                                                                                                                            summary['by_category'] = category_summary
                                                                                                                                                    
                                                                                                                                                            # สรุปรายเดือน
                                                                                                                                                                    monthly_summary = self.db.get_monthly_summary()
                                                                                                                                                                            summary['monthly'] = monthly_summary
                                                                                                                                                                                    
                                                                                                                                                                                            # สรุปรวม
                                                                                                                                                                                                    total_expense = sum(item[1] for item in category_summary if item[0] != 'รายได้')
                                                                                                                                                                                                            total_income = sum(item[1] for item in category_summary if item[0] == 'รายได้')
                                                                                                                                                                                                                    net_total = total_income - total_expense
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    summary['totals'] = {
                                                                                                                                                                                                                                                'total_expense': total_expense,
                                                                                                                                                                                                                                                            'total_income': total_income,
                                                                                                                                                                                                                                                                        'net_total': net_total
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                return summary
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        def get_categories(self):
                                                                                                                                                                                                                                                                                                                """ดึงประเภทรายการ"""
                                                                                                                                                                                                                                                                                                                        return self.db.get_categories()
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                def export_to_csv(self, filename):
                                                                                                                                                                                                                                                                                                                                        """ส่งออกข้อมูลเป็น CSV"""
                                                                                                                                                                                                                                                                                                                                                data = self.load_data_from_db()
                                                                                                                                                                                                                                                                                                                                                        df = pd.DataFrame(data, columns=['ID', 'ชื่อ', 'ประเภท', 'จำนวนเงิน', 'วันที่', 'รายละเอียด'])
                                                                                                                                                                                                                                                                                                                                                                df.to_csv(filename, index=False, encoding='utf-8-sig')
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                        def export_to_json(self, filename):
                                                                                                                                                                                                                                                                                                                                                                                """ส่งออกข้อมูลเป็น JSON"""
                                                                                                                                                                                                                                                                                                                                                                                        data = self.load_data_from_db()
                                                                                                                                                                                                                                                                                                                                                                                                formatted_data = []
                                                                                                                                                                                                                                                                                                                                                                                                        for item in data:
                                                                                                                                                                                                                                                                                                                                                                                                                    formatted_data.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                    'id': item[0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    'name': item[1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'category': item[2],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'amount': item[3],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'date': item[4],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'description': item[5]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(filename, 'w', encoding='utf-8') as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    json.dump(formatted_data, f, ensure_ascii=False, indent=4)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    